import { ROLES } from "./roles";

export const PERMISSIONS = {
  MANAGE_USERS: [ROLES.SUPER_ADMIN],
  MANAGE_MANAGERS: [ROLES.SUPER_ADMIN],
  MANAGE_MENU: [ROLES.SUPER_ADMIN],
  MANAGE_RESTAURANT_SETTINGS: [ROLES.SUPER_ADMIN],
  VIEW_ALL_REPORTS: [ROLES.SUPER_ADMIN],

  SCAN_QR: [ROLES.MANAGER],
  CREATE_ORDER: [ROLES.SUPER_ADMIN, ROLES.MANAGER],
  VIEW_FINANCIAL_DASHBOARD: [ROLES.SUPER_ADMIN, ROLES.MANAGER],

  USE_SALARY_DEDUCTION: [ROLES.CLIENT],
  VIEW_OWN_QR: [ROLES.CLIENT],
  VIEW_OWN_INVOICES: [ROLES.CLIENT, ROLES.MANAGER, ROLES.SUPER_ADMIN],
};

export function hasPermission(role, permissionKey) {
  const allowed = PERMISSIONS[permissionKey];
  if (!allowed) return false;
  return allowed.includes(role);
}